server:
  port: 8088

spring:
  web:
    resources:
      static-locations: classpath:/static
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
